CREATE OR REPLACE PROCEDURE CREATE_TABLE_AND_SEQUANCE AS
BEGIN

EXECUTE IMMEDIATE'
CREATE TABLE MEMBERSHIP_TABLE(
    MEMBERSHIP_IDX NUMBER PRIMARY KEY,
    MEMBERSHIP_GRADE VARCHAR2(10),
    MEMBERSHIP_POINT NUMBER
)';

EXECUTE IMMEDIATE'
INSERT INTO MEMBERSHIP_TABLE(MEMBERSHIP_IDX, MEMBERSHIP_GRADE, MEMBERSHIP_POINT) VALUES(0, ''비회원'', 0)';
EXECUTE IMMEDIATE'
INSERT INTO MEMBERSHIP_TABLE(MEMBERSHIP_IDX, MEMBERSHIP_GRADE, MEMBERSHIP_POINT) VALUES(1, ''BRONZE'', 0.1)';
EXECUTE IMMEDIATE'
INSERT INTO MEMBERSHIP_TABLE(MEMBERSHIP_IDX, MEMBERSHIP_GRADE, MEMBERSHIP_POINT) VALUES(2, ''SILVER'', 0.3)';
EXECUTE IMMEDIATE'
INSERT INTO MEMBERSHIP_TABLE(MEMBERSHIP_IDX, MEMBERSHIP_GRADE, MEMBERSHIP_POINT) VALUES(3, ''GOLD'', 0.5)';
EXECUTE IMMEDIATE'
INSERT INTO MEMBERSHIP_TABLE(MEMBERSHIP_IDX, MEMBERSHIP_GRADE, MEMBERSHIP_POINT) VALUES(4, ''PLATINUM'', 1)';

EXECUTE IMMEDIATE'
CREATE TABLE USER_TABLE(
    USER_IDX NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(60 BYTE) NOT NULL,
    USER_PW VARCHAR2(60 BYTE) NOT NULL,
    USER_NAME VARCHAR2(21 BYTE) NOT NULL,
    USER_EMAIL VARCHAR2(85 BYTE) NOT NULL,
    USER_PHONE VARCHAR2(39 BYTE) NOT NULL,
    USER_ROLE VARCHAR2(3 BYTE) DEFAULT ''D'' NOT NULL,
    USER_AVAILABLE VARCHAR2(3 BYTE) DEFAULT ''T'' NOT NULL,
    USER_DAILY NUMBER DEFAULT 0 NOT NULL,
    MEMBERSHIP_IDX NUMBER REFERENCES MEMBERSHIP_TABLE(MEMBERSHIP_IDX) NOT NULL,
    USER_BIRTH VARCHAR2(20 BYTE),
    USER_PROFILE_IMG VARCHAR2(90 BYTE),
    USER_PROFILE_TEXT VARCHAR2(150 BYTE),
    TOTAL_USER_POINT NUMBER DEFAULT 0 NOT NULL,
    USED_USER_POINT NUMBER DEFAULT 0 NOT NULL,
    MONTHLY_SPENDING NUMBER DEFAULT 0 NOT NULL,
    DOWNGRADE_WARNING NUMBER DEFAULT 3 NOT NULL,
    LAST_UPDATED DATE DEFAULT SYSDATE
)';

EXECUTE IMMEDIATE'
CREATE TABLE SELLER_TABLE(
    SELLER_IDX NUMBER PRIMARY KEY,
    SELL_CALC_NUM NUMBER DEFAULT 0 NOT NULL,
    SELL_CALC_ACCOUNT VARCHAR2(60),
    SELLING_PAGE_TITLE VARCHAR2(60),
    USER_IDX NUMBER REFERENCES USER_TABLE(USER_IDX) NOT NULL,
    SELLER_AVAILABLE VARCHAR2(3) DEFAULT ''T'' NOT NULL
)';

EXECUTE IMMEDIATE'
CREATE TABLE GOODS_TABLE(
    GOODS_IDX NUMBER PRIMARY KEY,
    GOODS_NAME VARCHAR2(120),
    GOODS_TAG VARCHAR2(15),
    GOODS_PRICE NUMBER,
    GOODS_IMG VARCHAR2(90),
    GOODS_STOCK NUMBER,
    GOODS_AVAILABLE VARCHAR2(3),
    SELLER_IDX NUMBER REFERENCES SELLER_TABLE(SELLER_IDX) NOT NULL,
    GOODS_IMG2 VARCHAR2(90),
    GOODS_TEXT VARCHAR2(600),
    REPORT_COUNT NUMBER
)';

EXECUTE IMMEDIATE'
CREATE TABLE ADDR_TABLE(
    ADDR_IDX NUMBER PRIMARY KEY,
    USER_IDX NUMBER REFERENCES USER_TABLE(USER_IDX) NOT NULL,
    USER_ADDR VARCHAR2(150),
    USER_POST VARCHAR2(24),
    ADDR_NAME VARCHAR2(30),
    ADDR_MAIN VARCHAR2(3),
    ADDR_PHONE VARCHAR2(30)
)';

EXECUTE IMMEDIATE'
CREATE TABLE CART_TABLE(
    CART_IDX NUMBER PRIMARY KEY,
    GOODS_IDX NUMBER REFERENCES GOODS_TABLE(GOODS_IDX) NOT NULL,
    USER_IDX NUMBER REFERENCES USER_TABLE(USER_IDX) NOT NULL,
    GOODS_QUANTITY NUMBER,
    SELECTED_OPTION VARCHAR2(30),
    CART_PRICE NUMBER
)';

EXECUTE IMMEDIATE'
CREATE TABLE WISH_TABLE(
    WISH_IDX NUMBER PRIMARY KEY,
    GOODS_IDX NUMBER REFERENCES GOODS_TABLE(GOODS_IDX) NOT NULL,
    USER_IDX NUMBER REFERENCES USER_TABLE(USER_IDX) NOT NULL
)';

EXECUTE IMMEDIATE'
CREATE TABLE NOTICE_TABLE(
    NOTICE_IDX NUMBER PRIMARY KEY,
    NOTICE_TITLE VARCHAR2(180),
    NOTICE_TEXT VARCHAR2(600),
    NOTICE_WRITER_IDX VARCHAR2(20),
    NOTICE_DATE DATE
)';

EXECUTE IMMEDIATE'
CREATE TABLE ADMIN_TABLE(
    ADMIN_IDX NUMBER PRIMARY KEY,
    ADMIN_ID VARCHAR2(60),
    ADMIN_PW VARCHAR2(60),
    ADMIN_TASK NUMBER
)';

EXECUTE IMMEDIATE'
INSERT INTO ADMIN_TABLE VALUES(1, ''ADMIN'', ''AdminPassWord'', 1)';

EXECUTE IMMEDIATE'
CREATE TABLE REVIEW_TABLE(
    REVIEW_IDX NUMBER PRIMARY KEY,
    REVIEW_TITLE VARCHAR2(30) DEFAULT ''무제'' NOT NULL,
    REVIEW_SCORE NUMBER DEFAULT 0 NOT NULL,
    REVIEW_IMG VARCHAR2(90),
    REVIEW_CONTENT VARCHAR2(150) NOT NULL,
    GOODS_IDX NUMBER REFERENCES GOODS_TABLE(GOODS_IDX) NOT NULL,
    USER_IDX NUMBER REFERENCES USER_TABLE(USER_IDX) NOT NULL,
    REVIEW_DATE DATE
)';

EXECUTE IMMEDIATE'
CREATE TABLE REPORT_TABLE(
    REPORT_IDX NUMBER PRIMARY KEY,
    GOODS_IDX NUMBER REFERENCES GOODS_TABLE(GOODS_IDX) NOT NULL,
    SELLER_IDX NUMBER NOT NULL
)';

EXECUTE IMMEDIATE'
CREATE TABLE OPTION_TABLE(
    OPTION_IDX NUMBER PRIMARY KEY,
    OPTION_NAME VARCHAR2(60),
    OPTION_PRICE NUMBER,
    GOODS_IDX NUMBER REFERENCES GOODS_TABLE(GOODS_IDX) NOT NULL
)';

EXECUTE IMMEDIATE'
CREATE TABLE BANNER_TABLE(
    BANNER_IDX NUMBER PRIMARY KEY,
    BANNER_NAME VARCHAR2(40),
    BANNER_IMG VARCHAR2(150),
    BANNER_STATUS NUMBER,
    BANNER_CNT NUMBER,
    GOODS_IDX NUMBER,
    GOODS_NAME VARCHAR2(60)
)';

EXECUTE IMMEDIATE'
CREATE TABLE SELLER_JOIN_INFO_TABLE(
    JOIN_INFO_IDX NUMBER PRIMARY KEY,
    SELLER_NAME VARCHAR2(30),
    SELLER_ID VARCHAR2(60),
    SELLER_EMAIL VARCHAR2(90),
    SELLER_PHONE VARCHAR2(45),
    SELLER_PAGE_TITLE VARCHAR2(60),
    CALC_ACCOUNT VARCHAR2(60),
    GOODS_TAG VARCHAR2(60),
    SAMPLE_IMG VARCHAR2(60),
    USER_IDX NUMBER
)';

EXECUTE IMMEDIATE'
CREATE TABLE ADD_GOODS_INFO_TABLE(
    INFO_IDX NUMBER PRIMARY KEY,
    GOODS_NAME VARCHAR2(120),
    GOODS_TAG VARCHAR2(30),
    GOODS_PRICE NUMBER,
    GOODS_IMG VARCHAR2(90),
    GOODS_INFO VARCHAR2(150),
    SELLER_IDX NUMBER,
    GOODS_IMG2 VARCHAR2(90)
)';

EXECUTE IMMEDIATE'
CREATE TABLE ORDER_TABLE(
    ORDER_IDX VARCHAR2(45) PRIMARY KEY,
    ORDER_DATE DATE,
    ADDR_IDX NUMBER REFERENCES ADDR_TABLE(ADDR_IDX) NOT NULL,
    USER_IDX NUMBER REFERENCES USER_TABLE(USER_IDX) NOT NULL,
    ORDER_MESSAGE VARCHAR2(90) DEFAULT ''메모가 없어요'',
    ORDER_STAT VARCHAR2(3),
    SELLER_IDX NUMBER NOT NULL,
    USED_POINT NUMBER DEFAULT 0,
    ADD_POINT NUMBER NOT NULL
)';

EXECUTE IMMEDIATE'
CREATE TABLE ORDER_GOODS_TABLE(
    ORDER_GOODS_IDX NUMBER PRIMARY KEY,
    ORDER_GOODS_NUM NUMBER,
    PRICE NUMBER,
    SELECTED_OPTION VARCHAR2(30),
    GOODS_IDX NUMBER REFERENCES GOODS_TABLE(GOODS_IDX) NOT NULL,
    ORDER_IDX VARCHAR2(45) REFERENCES ORDER_TABLE(ORDER_IDX) NOT NULL
)';

EXECUTE IMMEDIATE'
CREATE SEQUENCE USER_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE SELLER_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE GOODS_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE ADDR_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE CART_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE WISH_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE NOTICE_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE ADMIN_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE REVIEW_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE REPORT_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE OPTION_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE BANNER_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE SELLER_JOIN_INFO_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE ADD_GOODS_INFO_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

EXECUTE IMMEDIATE'
CREATE SEQUENCE ORDER_GOODS_SEQ
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1';

END CREATE_TABLE_AND_SEQUANCE;
